on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        node-version: [20.x]
        go-version: [1.25.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: build go lib against pinned dependency
      run: |
        go mod download
        go build ./...
    - name: npm install
      run: npm install
    - name: test
      run: npm test
