on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x]
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install go lib
      run: go get github.com/benitogf/ooo
    - name: npm install
      run: npm install
    - name: test
      run: npm test
